# Generated by Django 5.2.1 on 2025-05-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_initial_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
