# Generated by Django 5.2.1 on 2025-06-05 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_followmodel_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followmodel',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
